name = "retro-url-shortener"
compatibility_date = "2025-12-28"
compatibility_flags = [ "nodejs_compat" ]
main = "src/index.tsx"

[[kv_namespaces]]
binding = "LINKS"
id = "b0663926ace645debad31574448845f7"